global class ProfileDTO {
    public String id;
    public String name;
    public String title;
    public String titleEn;
    public String bio;
    public String bioEn;
    public String profileImageUrl;
    public String linkedInUrl;
    public String githubUrl;
    public String trailheadUrl;
    public String email;
    public String phone;
    public String whatsappPhone;
    public Decimal yearsExperience;
    public String location;
}
