global class ProjectDTO {
    public String id;
    public String name;
    public String nameEn;
    public String description;
    public String descriptionEn;
    public String shortDescription;
    public String shortDescriptionEn;
    public String slug;
    public String architectureNotes;
    public String imageUrl;
    public String githubUrl;
    public String projectUrl;
    public Boolean isFeatured;
    public String profileId;
    public List<String> techStack;
}
